name: build perl

on: [push]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-16.04
        perl:
        - "5.30.0"
        - "5.28.2"
        - "5.26.3"
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        curl -sL https://raw.githubusercontent.com/tokuhirom/Perl-Build/master/perl-build > "$RUNNER_TEMP/perl-build"
        MINOR_VERSION=$(echo -n $(echo $PERL_VERSION | cut -d. -f1,2))
        echo $MINOR_VERSION
        perl "$RUNNER_TEMP/perl-build" "$PERL_VERSION" "$RUNNER_TOOL_CACHE/perl/$MINOR_VERSION/x64" --noman
      env:
        PERL_VERSION: ${{ matrix.perl }}

  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-2019
        - windows-2016
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
