name: Main workflow
on:
  pull_request: {}
  push:
    branches-ignore:
      - "releases/*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-2019
          - macos-10.15
        dist:
          - default
          - strawberry
    steps:
      - name: disable autocrlf
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm run build
      - run: npm run package
      - run: npm test

      - name: use the action
        uses: ./
        with:
          perl-version: "5.30.0"
          distribution: ${{ matrix.dist }}
      - run: perl -V
      - run: gcc --version

      - run: npm run format-check
